set_property PACKAGE_PIN J6 [get_ports io_PMOD_1]
set_property IOSTANDARD LVCMOS18 [get_ports io_PMOD_1]

set_property PACKAGE_PIN J5 [get_ports io_PMOD_3]
set_property IOSTANDARD LVCMOS18 [get_ports io_PMOD_3]

set_property PACKAGE_PIN K9 [get_ports io_PMOD_4]
set_property IOSTANDARD LVCMOS18 [get_ports io_PMOD_4]

set_property PACKAGE_PIN N9 [get_ports io_PMOD_10]
set_property IOSTANDARD LVCMOS18 [get_ports io_PMOD_10]

set_property IOSTANDARD LVCMOS18 [get_ports {o_AXI_ADC_Data_Last[0]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {o_AXI_ADC_Data_Out[15]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {o_AXI_ADC_Data_Out[14]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {o_AXI_ADC_Data_Out[13]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {o_AXI_ADC_Data_Out[12]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {o_AXI_ADC_Data_Out[11]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {o_AXI_ADC_Data_Out[10]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {o_AXI_ADC_Data_Out[9]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {o_AXI_ADC_Data_Out[8]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {o_AXI_ADC_Data_Out[7]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {o_AXI_ADC_Data_Out[6]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {o_AXI_ADC_Data_Out[5]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {o_AXI_ADC_Data_Out[4]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {o_AXI_ADC_Data_Out[3]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {o_AXI_ADC_Data_Out[2]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {o_AXI_ADC_Data_Out[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_AXI_ADC_Data_Out[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_AXI_ADC_Data_Valid[0]}]

set_property PACKAGE_PIN D1 [get_ports {o_AXI_ADC_Data_Last[0]}]
#set_property PACKAGE_PIN D2 [get_ports {o_AXI_ADC_Data_Out[15]}]
#set_property PACKAGE_PIN D4 [get_ports {o_AXI_ADC_Data_Out[14]}]
#set_property PACKAGE_PIN D5 [get_ports {o_AXI_ADC_Data_Out[13]}]
#set_property PACKAGE_PIN D6 [get_ports {o_AXI_ADC_Data_Out[12]}]
#set_property PACKAGE_PIN D7 [get_ports {o_AXI_ADC_Data_Out[11]}]
#set_property PACKAGE_PIN D9 [get_ports {o_AXI_ADC_Data_Out[10]}]
#set_property PACKAGE_PIN E1 [get_ports {o_AXI_ADC_Data_Out[9]}]
#set_property PACKAGE_PIN E2 [get_ports {o_AXI_ADC_Data_Out[8]}]
#set_property PACKAGE_PIN E3 [get_ports {o_AXI_ADC_Data_Out[7]}]
#set_property PACKAGE_PIN E4 [get_ports {o_AXI_ADC_Data_Out[6]}]
#set_property PACKAGE_PIN E5 [get_ports {o_AXI_ADC_Data_Out[5]}]
#set_property PACKAGE_PIN E7 [get_ports {o_AXI_ADC_Data_Out[4]}]
#set_property PACKAGE_PIN E8 [get_ports {o_AXI_ADC_Data_Out[3]}]
#set_property PACKAGE_PIN E9 [get_ports {o_AXI_ADC_Data_Out[2]}]
#set_property PACKAGE_PIN F1 [get_ports {o_AXI_ADC_Data_Out[1]}]
set_property PACKAGE_PIN F2 [get_ports {o_AXI_ADC_Data_Out[0]}]
set_property PACKAGE_PIN F3 [get_ports {o_AXI_ADC_Data_Valid[0]}]
